---

- name: disable qxl
  hosts:
      - routers
      - hosts
  gather_facts: yes
  become: yes
  tasks:
      - include_role:
            name: kypo-disable-qxl
        when: ansible_os_family == 'Debian'

- name: set up server
  hosts: server
  become: yes
  roles:
    - name: server

- name: set up client
  hosts: client
  become: yes
  roles:
    - name: kypo-user-access
      kypo_user_access_username: user
      kypo_user_access_password: Password123
      kypo_user_access_sudo: True
    - name: client

...
